<?php


/**
 * [BEGIN_COT_EXT]
 * Code=hybridauth
 * Name=HybridAuth
 * Category=community-social
 * Description=Social networks autorization
 * Version=1.0.0
 * Date=2012-10-10
 * Author=esclkm
 * Auth_guests=R
 * Lock_guests=12345A
 * Auth_members=RW
 * [END_COT_EXT]
 * 
 * [BEGIN_COT_EXT_CONFIG]
 * providers=01:textarea:::List Providers
 * autoreg=02:radio::1:Enabled auto registration?
 * disablemanualreg=03:radio::1:Disable manual registration?
 * remember=04:radio::1:Remember the user for Auto Login?
 * s_mail=07:radio:0,1:0:Send message?
 * [END_COT_EXT_CONFIG]
 * 
 *  */

/**
 * plugin HybridAuth for Cotonti Siena
 * 
 * @package hybridauth
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL');

?>