<?php

/** 
 * [BEGIN_COT_EXT]
 * Hooks=users.register.tags
 * [END_COT_EXT]
 */
 
/**
 * plugin HybridAuth for Cotonti Siena
 * 
 * @package hybridauth
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');

require_once cot_langfile('hybridauth', 'plug');
require_once cot_incfile('hybridauth', 'plug');


?>